#!/usr/bin/env bash
set -euo pipefail

OUT="traefik/dynamic/cloudflare-ips.yml"
TMP="$(mktemp "${OUT}.XXXXXX")"
trap 'rm -f "$TMP"' EXIT

{
  echo "# AUTO-GENERATED by scripts/update-cf-ips.sh"
  echo "# Source: https://www.cloudflare.com/ips-v4  https://www.cloudflare.com/ips-v6"
  echo "# DO NOT EDIT MANUALLY. Re-run 'make update-cf-ips' to refresh."
  echo "#"
  echo "# NOTE: ipStrategy is intentionally NOT set. Traefik checks RemoteAddr (TCP peer),"
  echo "# not X-Forwarded-For. All HTTPS traffic on websecure arrives via a single hop from"
  echo "# the CF edge, so the TCP source IP equals the CF edge IP. Using depth:1 would read"
  echo "# the last XFF header entry which a client can forge."
  echo "http:"
  echo "  middlewares:"
  echo "    cloudflare-only:"
  echo "      ipAllowList:"
  echo "        sourceRange:"
  curl -fsSL https://www.cloudflare.com/ips-v4 | sed 's/^/          - /'
  curl -fsSL https://www.cloudflare.com/ips-v6 | sed 's/^/          - /'
} > "$TMP"

# basic sanity: at least one CIDR line, otherwise abort
if ! grep -Eq '^ *- [0-9a-fA-F:.]+/[0-9]+' "$TMP"; then
  echo "ERROR: no CIDR ranges fetched — aborting, not overwriting $OUT" >&2
  exit 1
fi

mv "$TMP" "$OUT"
trap - EXIT
echo "Updated $OUT"
